### ISSUE TITLE
should compile to js instead of jsx

### ISSUE THREAD

**Issue by tony1223** [appleboy/react-recaptcha#7]
if we require this one in webpack or something like that it will be fail.

I think it should convert jsx  to js file to be working in more environment.

/*
/private/var/clones/interest_workspace/budget/node_modules/react-recaptcha/src/index.js:41
        <div id={this.props.elementID}
        ^
SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/private/var/clones/interest_workspace/budget/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/clones/interest_workspace/budget/views/controller/user/signup.jsx:3:65)
    at Module._compile (module.js:460:26)
*/

for how to convert, here's a simple tool
https://goo.gl/mxKebV

**Comment by appleboy** [comment]
@tony1223 Good catch. I will take it.

**Comment by appleboy** [comment]
@tony1223 Please install version `1.0.0` again.
